### ISSUE TITLE
Can’t go to the main link from a forked link

### ISSUE THREAD

**Issue by gios2** [pupgray/walltaker#35]
when the button at the top of the forked links is clicked to go to the main link, "content missing" is showed and don’t change page
from the browser devtools console it says:

>  turbo.es2017-esm.js:3650 Uncaught (in promise) Error: The response (200) did not contain the expected < turbo-frame id="link_14015" > and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.

**Comment by pupgray** [comment]
Solved!
